In [4]:
import numpy as np
x=np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
y=[1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [6]:
%timeit [j**4 for j in range(1,8)]

745 ns ± 126 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [7]:
import numpy as np
%timeit np.arange(1,9)**4

2.25 μs ± 129 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [1]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
import numpy as np
x=[1,2,3,4,5,6]
y=np.array(x)
y

array([1, 2, 3, 4, 5, 6])

In [6]:
l=[]
for i in range(1,5):
    int_1=int(input("Enter :"))
    l.append(int_1)
    print(np.array(l))

Enter : 12


[12]


Enter : 13


[12 13]


Enter : 14


[12 13 14]


Enter : 15


[12 13 14 15]


In [8]:
import numpy as np
x=[1,2,3,4]
y=np.array([1,2,3,4,5])
print(y.ndim)

1


In [11]:
ar2=np.array([[1,2,3,4],[1,2,3,4]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [12]:
ar3=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [15]:
arn=np.array ([1,2,3,4],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [34]:
import numpy as np
ar_zero= np.zeros((3,2,4))
print(ar_zero)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [27]:
ar_one=np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


In [36]:
ar_em=np.empty(0)
print(ar_em)

[]


In [39]:
ar_rn=np.arange(1,4,2)
print(ar_rn)

[1 3]


In [43]:
ar_dia=np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [55]:
ar_lin=np.linspace(2,18,num=5)
print(ar_lin)

[ 2.  6. 10. 14. 18.]


In [2]:
import numpy as np
var=np.random.rand(4)
print(var)

[0.05003102 0.92305026 0.29715692 0.14656534]


In [11]:
import numpy as np
var1=np.random.rand(2,5)
print(var1)

[[0.51169828 0.37679189 0.14665055 0.4545842  0.03703666]
 [0.53823935 0.6163021  0.12567016 0.94780169 0.88178676]]


In [4]:
var2=np.random.randn(4)
print(var2)

[-2.68365013  0.25479762 -0.07738717 -1.50139453]


In [13]:
var3=np.random.ranf((2,3))
print(var3)

[[0.99074631 0.28022646 0.81382387]
 [0.71341881 0.70293078 0.98257555]]


In [14]:
var4=np.random.randint(5,20,5)
print(var4)

[10 12  7 14 13]


In [18]:
import numpy as np
var=np.array([1,2,3,4,13])
print("data type : ",var.dtype)

data type :  int64


In [19]:
var=np.array([1.22,2.44,3.76,4.88,13.00])
print("data type : ",var.dtype)

data type :  float64


In [24]:
var=np.array(["A","D","R","F",1,2,3,4])
print("data type : ",var.dtype)

data type :  <U21


In [25]:
var=np.array(["A","D","R","F"])
print(var.dtype)

<U1


In [30]:
x=np.array([1,2,3,4],dtype=np.int8)
print(x.dtype)
print(x)


int8
[1 2 3 4]


In [4]:
import numpy as np
x1=np.array([1,2,3,4,],dtype="f")
print(x1.dtype)
print(x1)


float32
[1. 2. 3. 4.]


In [32]:
x2=np.array([1,2,3,4])
new=np.float32(x2)
print(x2.dtype)
print(new.dtype)
print(x2)
print(new)

int64
float32
[1 2 3 4]
[1. 2. 3. 4.]


In [36]:
x2=np.array([1,2,3,4])
new=np.float32(x2)
new_one=np.int_(new)
print(x2.dtype)
print(new.dtype)
print(new_one.dtype)
print(x2)
print(new)
print(new_one)

int64
float32
int64
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [38]:
x3=np.array([1,2,3,4])
new_1=x3.astype(float)
print(x3)
print(new_1)
print(new_1.dtype)

[1 2 3 4]
[1. 2. 3. 4.]
float64


In [1]:
import numpy as np
var=np.array([1,2,3,4])
varadd=var+3
print(varadd)

[4 5 6 7]


In [2]:
import numpy as np
var1=np.array([1,2,3,4])
var2=np.array([1,2,3,4])
varadd=var1+var2
print(varadd)

[2 4 6 8]


In [3]:
import numpy as np
var=np.array([1,2,3,4])
varsub=var-3
print(varsub)

[-2 -1  0  1]


In [7]:
import numpy as np
var=np.array([1,2,3,4])
varsub=var-3
print(varsub)

[-2 -1  0  1]


In [8]:
import numpy as np
var=np.array([1,2,3,4])
varsub=var*3
print(varsub)

[ 3  6  9 12]


In [9]:
import numpy as np
var=np.array([1,2,3,4])
varsub=var/3
print(varsub)

[0.33333333 0.66666667 1.         1.33333333]


In [10]:
import numpy as np
var=np.array([1,2,3,4])
varsub=var%3
print(varsub)

[1 2 0 1]


In [15]:
import numpy as np
var1=np.array([1,2,3,4])
var2=np.array([1,2,3,4])
varadd=np.add(var1,3)
print(varadd)

[4 5 6 7]


In [26]:
import numpy as np
var1=np.array([1,2,3,4])
var2=np.array([5,6,7,9])
varrec=np.reciprocal(var1)
print(varrec)

[1 0 0 0]


In [28]:
import numpy as np
var21=np.array([[1,2,3,4],[1,2,3,4]])
var22=np.array([[1,2,3,4],[1,2,3,4]])
varmul2=var21*var22
print(varmul2)

[[ 1  4  9 16]
 [ 1  4  9 16]]


In [37]:
import numpy as np
var=np.array([1,2,3,4,5,3,2])
print("min :" ,np.min(var),"min position :", np.argmin(var))
print("max :" ,np.max(var),"max position :",np.argmax(var))


min : 1 min position : 0
max : 5 max position : 4


In [38]:
var1=np.array([[2,1,3],[9,5,6]])
print(np.min(var1,axis=1))



[1 5]


In [39]:
var1=np.array([[2,1,3],[9,5,6]])
print(np.min(var1,axis=0))


[2 1 3]


In [40]:
import numpy as np
var=np.array([1,2,3,4,5,3,2])
print("sqrt :", np.sqrt(var))

sqrt : [1.         1.41421356 1.73205081 2.         2.23606798 1.73205081
 1.41421356]


In [43]:
var2=np.array([1,2,3])
print(np.sin(var2))

[0.84147098 0.90929743 0.14112001]


In [44]:
var2=np.array([1,2,3])
print(np.cos(var2))

[ 0.54030231 -0.41614684 -0.9899925 ]


In [45]:
var2=np.array([1,2,3])
print(np.cumsum(var2))

[1 3 6]


In [15]:
import numpy as np
var=np.array([1,2,3,4])

print(var.shape)

(4,)


In [13]:
var1=np.array([1,2,3,4],ndmin=4)
print(var1)
print()
print(var1.ndim)
print()
print(var1.shape)

[[[[1 2 3 4]]]]

4

(1, 1, 1, 4)


In [18]:
var2=np.array([1,2,3,4,5,6])
print(var2.ndim)
x=var2.reshape(3,2,1)
print(x)
print(x.ndim)

1
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]
3


In [30]:
var2=np.array([1,2,3,4,5,6])
print(var2.ndim)
x=var2.reshape(3,2)
print(x)
print(x.ndim)
one=x.reshape(-1)
print(one)
print(one.ndim)

1
[[1 2]
 [3 4]
 [5 6]]
2
[1 2 3 4 5 6]
1


In [25]:
var3=np.array([1,2,3,4,5,6])
print(var3.ndim)
x=var3.reshape(2,3,1)
print(x)
print(x.ndim)

1
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
3


In [28]:
var3=np.array([1,2,3,4,5,6])
print(var3.ndim)
x=var3.reshape(2,3,1)
print(x)
print(x.ndim)
print()
one=x.reshape(2,3)
print(one)
print(one.ndim)

1
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
3

[[1 2 3]
 [4 5 6]]
2


In [36]:
import numpy as np
var1=np.array([1,2,3])
print(var1.shape)
print(var1)
print()

var2=np.array([[1],[2],[3]])
print(var2.shape)
print(var2)
print()
print(var1+var2)

(3,)
[1 2 3]

(3, 1)
[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [40]:
x=np.array([[1],[2]])
print(x.shape)
y=np.array([[1,2,3],[4,5,6]])
print(y.shape)

print(x+y)


(2, 1)
(2, 3)
[[2 3 4]
 [6 7 8]]


In [3]:
import numpy as np

var=np.array([9,8,7,6])
#             0,1,2,3
#            -4,-3,-2,-1
print(var[1])
print(var[-3])

8
8


In [6]:
var1=np.array([[9,8,7],[4,5,6]])
print(var1)
print(var1.ndim)
print()

print(var1[0,2])


[[9 8 7]
 [4 5 6]]
2

7


In [15]:
var2=np.array([[[1,2],[6,7]]])
print(var2)
print(var2.ndim)
print()
print(var2[0,1,1])

[[[1 2]
  [6 7]]]
3

7


In [21]:
import numpy as np
var1=np.array([1,2,3,4,5,6,7])
#              0,1,2,3,4,5,6
print(var1)
print()
print(var1[1:])
print(var1[::2])
print(var1[1:5:2])


[1 2 3 4 5 6 7]

[2 3 4 5 6 7]
[1 3 5 7]
[2 4]


In [33]:
var2=np.array([[9,8,7,6],[11,12,13,14],[15,16,17,18]])
print (var2[2,1:])
print (var2[0,1:3])



[16 17 18]
[8 7]


In [39]:
var3=np.array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],      
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],      
        [20, 21, 22, 23]]])

print(var3[0,2,1:3])

[ 9 10]


In [41]:
import numpy as np
var=np.array([9,8,7,6,5,4])
print(var)
print()
for i in var:
    print(i)

[9 8 7 6 5 4]

9
8
7
6
5
4


In [44]:
var1=np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()
for j in var1:
   print(j)

[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4]
[1 2 3 4]


In [48]:
var1=np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()
for  k in var1:
    for l in k:
        print(l)

[[1 2 3 4]
 [1 2 3 4]]

1
2
3
4
1
2
3
4


In [49]:
var3=np.array([[[1,2,3,4],[1,2,3,4]]])
print(var3)
print(var3.ndim)
print()
for i in var3:
    print(i)
print()
for  j in var3:
    for k in j:
        for l in k:
            print(l)

[[[1 2 3 4]
  [1 2 3 4]]]
3

[[1 2 3 4]
 [1 2 3 4]]

1
2
3
4
1
2
3
4


In [50]:
var3=np.array([[[1,2,3,4],[1,2,3,4]]])
print(var3)
print(var3.ndim)
print()

for i in np.nditer(var3):
    print(i)

[[[1 2 3 4]
  [1 2 3 4]]]
3

1
2
3
4
1
2
3
4


In [55]:
var3=np.array([[[1,2,3,4],[1,2,3,4]]])
print(var3)
print(var3.ndim)
print()

for i in np.nditer(var3):
    print(i)

[[[1 2 3 4]
  [1 2 3 4]]]
3

1
2
3
4
1
2
3
4


In [58]:
var3=np.array([[[1,2,3,4],[1,2,3,4]]])
print(var3)
print(var3.ndim)
print()

for i,d in np.ndenumerate(var3):
    print(i,d)

[[[1 2 3 4]
  [1 2 3 4]]]
3

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4


In [5]:
import numpy as np
var=np.array([1,2,3,4])
co=var.copy()
var[1]=40
print("var :",var)
print("copy :",co)


var : [ 1 40  3  4]
copy : [1 2 3 4]


In [6]:
x=np.array([9,8,7,6,5])
vi=x.view()
x[1]=32
print("x :",x)
print("view :",vi)

x : [ 9 32  7  6  5]
view : [ 9 32  7  6  5]


In [7]:
import numpy as np
var=np.array([1,2,3,4])
var1=np.array([9,8,7,6])
ar=np.concatenate((var,var1))
print(ar)

[1 2 3 4 9 8 7 6]


In [15]:
vr=np.array([[1,2],[3,4]])
vr1=np.array([[9,8],[7,6]])
ar_new=np.concatenate((vr,vr1),axis=0)
ar_new1=np.concatenate((vr,vr1),axis=1)
print(vr)
print()
print(vr1)
print()
print(ar_new)
print()
print(ar_new1)



[[1 2]
 [3 4]]

[[9 8]
 [7 6]]

[[1 2]
 [3 4]
 [9 8]
 [7 6]]

[[1 2 9 8]
 [3 4 7 6]]


In [21]:
vr=np.array([[[1,2]],[[3,4]]])
vr1=np.array([[[9,8]],[[7,6]]])
ar_new=np.concatenate((vr,vr1),axis=0)
ar_new1=np.concatenate((vr,vr1),axis=1)
ar_new2=np.concatenate((vr,vr1),axis=2)
print()
print(ar_new)
print()
print(ar_new1)
print()
print(ar_new2)


[[[1 2]]

 [[3 4]]

 [[9 8]]

 [[7 6]]]

[[[1 2]
  [9 8]]

 [[3 4]
  [7 6]]]

[[[1 2 9 8]]

 [[3 4 7 6]]]


In [33]:
vr_1=np.array([1,2,3,4])
vr_2=np.array([9,8,7,6])
a_new=np.stack((vr_1,vr_2),axis=1)
a_new1=np.hstack((vr_1,vr_2)) #row
a_new2=np.vstack((vr_1,vr_2)) #column
a_new3=np.dstack((vr_1,vr_2))  #height
print()
print(a_new)
print()
print(a_new1)
print()
print(a_new2)
print()
print(a_new3)


[[1 9]
 [2 8]
 [3 7]
 [4 6]]

[1 2 3 4 9 8 7 6]

[[1 2 3 4]
 [9 8 7 6]]

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


In [29]:
vr_1=np.array([1,2,3,4])
vr_2=np.array([9,8,7,6])
a_new2=np.vstack((vr_1,vr_2)) #column
print(a_new2)

[[1 2 3 4]
 [9 8 7 6]]


In [41]:
import numpy as np
var=np.array([1,2,3,4,5,6])
print(var)
ar=np.array_split(var,3)
print()
print(ar)
print(type(ar))
print(ar[0])

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>
[1 2]


In [62]:
var1=np.array([[[1,2]],[[3,4]],[[5,6]]])


ar2=np.array_split(var1,3,axis=1)
ar3=np.array_split(var1,3,axis=0)

print()
print(ar2)
print()
print(ar3)


[array([[[1, 2]],

       [[3, 4]],

       [[5, 6]]]), array([], shape=(3, 0, 2), dtype=int64), array([], shape=(3, 0, 2), dtype=int64)]

[array([[[1, 2]]]), array([[[3, 4]]]), array([[[5, 6]]])]


In [8]:
import numpy as np
var=np.array([1,2,3,4,2,5,2,5,6,7])
#index        0 1 2 3 4 5 6 7 8 9
x=np.where(var%2 ==0)
print(x)

(array([1, 3, 4, 6, 8]),)


In [23]:
var1=np.array([1,2,3,4,9,8])
#index         0 1 2 3 4 5 
x1=np.searchsorted(var1,[5,6,7],side="right")
print(x1)

[4 4 4]


In [25]:
var_1=np.array([4,2,3,1,12,5,22,52,6,7])
#index          0 1 2 3 4 5 6 7 8 9
print(np.sort(var_1))

[ 1  2  3  4  5  6  7 12 22 52]


In [26]:
var_2=np.array(["a","s","d","f"])
print(np.sort(var_2))

['a' 'd' 'f' 's']


In [28]:
var_1=np.array([[4,2,3],[1,12,5],[22,52,6]])

print(np.sort(var_1))

[[ 2  3  4]
 [ 1  5 12]
 [ 6 22 52]]


In [31]:
var_3=np.array(["a","s","d","f"])
f=[True,False,False,True]
new_a=var_3[f]
print(new_a)
print(type(new_a))


['a' 'f']
<class 'numpy.ndarray'>


In [32]:
import numpy as np
var=np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)

[5 1 2 4 3]


In [34]:
var1=np.array([1,2,3,4,2,5,2,6,2,7])
x=np.unique(var1)
print(x)

[1 2 3 4 5 6 7]


In [35]:
var1=np.array([1,2,3,4,2,5,2,6,2,7])
x=np.unique(var1,return_index=True,return_counts=True)
print(x)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 7, 9]), array([1, 4, 1, 1, 1, 1, 1]))


In [36]:
var2=np.array([1,2,3,4,5,6])
y=np.resize(var2,(2,3))
print(y)

[[1 2 3]
 [4 5 6]]


In [37]:
var2=np.array([1,2,3,4,5,6])
y=np.resize(var2,(3,2))
print(y)

[[1 2]
 [3 4]
 [5 6]]


In [41]:
var2=np.array([1,2,3,4,5,6])
y=np.resize(var2,(3,2))
print(y)
print()
print(y.flatten())

[[1 2]
 [3 4]
 [5 6]]

[1 2 3 4 5 6]


In [39]:
var2=np.array([1,2,3,4,5,6])
y=np.resize(var2,(3,2))
print(y)
print()
print(y.flatten(order="F"))

[[1 2]
 [3 4]
 [5 6]]

[1 3 5 2 4 6]


In [43]:
var2=np.array([1,2,3,4,5,6])
y=np.resize(var2,(3,2))
print(y)
print()
print(np.ravel(y))

[[1 2]
 [3 4]
 [5 6]]

[1 2 3 4 5 6]


In [44]:
var2=np.array([1,2,3,4,5,6])
y=np.resize(var2,(3,2))
print(y)
print()
print(np.ravel(y,order="F"))

[[1 2]
 [3 4]
 [5 6]]

[1 3 5 2 4 6]


In [46]:
var2=np.array([1,2,3,4,5,6])
y=np.resize(var2,(3,2))
print(y)
print()
print(np.ravel(y,order="K"))

[[1 2]
 [3 4]
 [5 6]]

[1 2 3 4 5 6]


In [8]:
import numpy as np
var=np.array([1,2,3,4])
print(var)
v=np.insert(var,(2,4),40)
print(v)

[1 2 3 4]
[ 1  2 40  3  4 40]


In [9]:
import numpy as np
var=np.array([1,2,3,4])
print(var)
v=np.insert(var,(2,4),6.5)
print(v)

[1 2 3 4]
[1 2 6 3 4 6]


In [10]:
var1=np.array([[1,2,3],[1,2,3]])
v1=np.insert(var1,2,6,axis=0)
print(v1)



[[1 2 3]
 [1 2 3]
 [6 6 6]]


In [11]:
var1=np.array([[1,2,3],[1,2,3]])
v1=np.insert(var1,2,6,axis=1)
print(v1)


[[1 2 6 3]
 [1 2 6 3]]


In [19]:
var1=np.array([[1,2,3],[1,2,3]])
v1=np.insert(var1,2,[22,23,24],axis=0)
print(v1)


[[ 1  2  3]
 [ 1  2  3]
 [22 23 24]]


In [21]:
var1=np.array([[1,2,3],[1,2,3]])
v1=np.insert(var1,2,[22,23],axis=1)
print(v1)

[[ 1  2 22  3]
 [ 1  2 23  3]]


In [27]:
import numpy as np
var=np.array([1,2,3,4,5,6])
print(var)
x=np.append(var,6.5)
print(x)



[1 2 3 4 5 6]
[1.  2.  3.  4.  5.  6.  6.5]


In [34]:
var1=np.array([[1,2,3],[1,2,3]])
v1=np.append(var1,[[45,44],[45,44]],axis=1)
print(v1)

[[ 1  2  3 45 44]
 [ 1  2  3 45 44]]


In [35]:
import numpy as np
var1=np.array([1,2,3,4])
print(var1)
d=np.delete(var1,2)
print(d)

[1 2 3 4]
[1 2 4]


In [38]:
import numpy as np

# Creating a 2D array
var2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

print("Original array:")
print(var2)

# Deleting the third row (index 2) from the 2D array
d = np.delete(var2,2, axis=1)
print("Array after deleting the third row:")
print(d)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array after deleting the third row:
[[ 1  2  4]
 [ 5  6  8]
 [ 9 10 12]]


In [42]:
import numpy as np
var=np.matrix([[1,2,3],[1,2,3]])
print(var)
print(type(var))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>


In [44]:
var1=np.array([[1,2,3],[1,2,3]])
print(var)
print(type(var1))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


In [50]:
import numpy as np
var=np.matrix([[1,2],[1,2]])
var2=np.matrix([[1,2],[1,2]])
print()
print(var.dot(var2))


[[3 6]
 [3 6]]


In [52]:
import numpy as np
var=np.array([[1,2],[1,2]])
var2=np.array([[1,2],[1,2]])
print()
print(var*var2)


[[1 4]
 [1 4]]


In [57]:
import numpy as np
var=np.matrix([[1,2,3],[4,5,6]])
print(var)
print()
print(np.transpose(var))
print()
print(var.T)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [59]:
var=np.matrix([[1,2,3],[4,5,6]])
print(var)

print()
print(np.swapaxes(var,0,1))


[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [60]:
var2=np.matrix([[1,2],[3,4]])
print(var2)
print()
print(np.swapaxes(var2,0,1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [61]:
var2=np.matrix([[1,2],[3,4]])
print()
print(var2)
print()
print(np.linalg.inv(var2))


[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [62]:
var3=np.matrix([[1,2],[3,4]])
print(var3)
print()
print(np.linalg.matrix_power(var3,2))

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]


In [63]:
var3=np.matrix([[1,2],[3,4]])
print(var3)
print()
print(np.linalg.matrix_power(var3,0))

[[1 2]
 [3 4]]

[[1 0]
 [0 1]]


In [64]:
var3=np.matrix([[1,2],[3,4]])
print(var3)
print()
print(np.linalg.matrix_power(var3,-2))

[[1 2]
 [3 4]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]


In [65]:
var4=np.matrix([[1,2],[3,4]])
print(var4)
print()
print(np.linalg.det(var4))


[[1 2]
 [3 4]]

-2.0000000000000004


In [74]:
var5=np.matrix([[1,2,3],[31,4,5],[6,77,8]])
print(var5)
print()
print(np.linalg.det(var5))


[[ 1  2  3]
 [31  4  5]
 [ 6 77  8]]

6299.999999999996


In [75]:
var6=np.matrix([[1,2,3],[31,4,5],[1,2,3]])
print(var6)
print()
print(np.linalg.det(var6))

[[ 1  2  3]
 [31  4  5]
 [ 1  2  3]]

0.0
